// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID         int     `json:"id"`
	Descricao  string  `json:"Descricao"`
	Preco      float64 `json:"Preco"`
	Taxa       float64 `json:"Taxa"`
	PrecoTotal float64 `json:"PrecoTotal"`
}

type OrderInput struct {
	Descricao string  `json:"Descricao"`
	Preco     float64 `json:"Preco"`
	Taxa      float64 `json:"Taxa"`
}
